///$tab SSCC
SERVICIOS_COMPLEMENTARIOS:
LOAD
    %KEY_BLOQUE_FUENTE_VERSION,
    %KEY_DICCIONARIO_CENTRALES,
    Fecha_Hora,
    Fecha,
    AñoMesNum,
    MesAño,
    Mes,
    Año,
    Semana,
    Dia,
    Hora,
    SSCC_SERVICIO,
    SSCC_SERVICIO_DESC,
    cantidad_mw,
    precio,
    banda,
    fuente,
    fecha_version,
    numero_version
FROM [lib://STG/PLATAFORMA PROGRAMACION/STG_PRG_SERVICIOS_COMPLEMENTARIOS.qvd]
(qvd);